project:
  type: website
  output-dir: docs

website:
  title: "Ecohydrology Lab Handbook"
  navbar:
    search: true
  sidebar: 
    style: "floating"
    contents: 
      - section: "Team Overview"
        contents:
          - values.qmd
          - team_contacts.qmd
      - section: "Team Guidelines"
        contents:
          - guidelines.qmd
          - authorship.qmd
          - field_equipment.qmd
      - section: "Resources"
        contents:
          - new_student_resources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

#Need to add (i) new students resources, (ii) mentoring resources, (iii) SOPs (just a page with links), (iv) graduation checklist

