project:
  type: website
  output-dir: docs

website:
  title: "Ecohydrology Lab Handbook"
  navbar:
    search: true
  sidebar: 
    style: "floating"
    contents: 
      - section: "Lab Overview"
        contents:
          - values.qmd
          - guidelines.qmd
           
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

