project:
  type: website
  output-dir: docs

website:
  title: "Ecohydrology Lab Handbook"
  navbar:
    search: true
  sidebar: 
    style: "floating"
    contents: 
      - section: "Team Overview"
        contents:
          - values.qmd
          - guidelines.qmd
          - team_contacts.qmd
      - section: "Shared Resources"
        contents:
          - cyber.qmd
          - field_equipment.qmd
          - lab_equipment.qmd
      - semester_admin_jobs.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

