---
title: "Team Guidelines"
---

1.  **We will prioritize personnel safety, research integrity, and team cohesion**.

2.  **We will promote a 'culture of safety' in our lab**. This includes taking responsibility for one's own safety, looking out for the safety of others, and having open/honest team discussions about minimizing risks.

3.  **Never go to the field alone.** This is non-negotiable.

4.  **We will conduct our research in an ethical manner**. As scientists, our credibility is one of our most important assets. Team members will not purposely plagiarize, deceptively manipulate or fabricate data, or take part in any unscrupulous research activities. 

5.  **We will work to support an atmosphere of inclusion**. All team members will work to build trust across our team, actively listening to all points of view, rigorously evaluating all ideas, and be both kind and empathetic when providing feedback.

6.  **We will strive towards effective communication**.  This means team members should:

    -   **Keep Team PI \[Nate Jones\] up-to-date on their research progress**. This can be done through weekly team meetings, weekly or twice-monthly individual meetings, and/or weekly updates via slack.

    -   **Communicate with other team-members about research infrastructure use.** We are a big lab that does a lot of field research. Team members should utilize lab calendars to schedule field truck and shared field equipment (i.e., laptop, YSI, etc). Notably, when overlap between resources comes up, team members should work together to develop an equitable plan to meet all parties needs. 

    -   **Communicate research issues**. Instruments will break, sondes will die, and the truck will get stuck. **Shit happens.** While team members should work to minimize these events, it's important to be transparent when they happen. When things break, notify Lab PI and also post it to "lab logistics" slack channel.

    -   **Communicate personnel problems**. There will be conflicts on our team. It's a natural part of team building, and when managed correctly, it can actually be productive. When conflict does arise, teammates are expected to treat each other with respect, listen to one-another, and work towards an equitable solution. In cases where a solution cannot be met, the Lab PI will work with team members to find a solution. 

7.  **Graduate and our research is a job, and we will treat it as such**. Expectations of team members include:

    -   **Work 40 hours a week (on average)**. For team members supported by UA, time allocation should be: 
        -   **50% Assigned Work.** This could include teaching assistant duties, community lab duties, attending team meetings, project specific duties, and other tasks assigned by Lab PI (i.e., field work unrelated to thesis/dissertation research, driving colleagues to the airport, etc). 
        -   **50% Research and Scholarly Activities**.This includes data collection, writing, and course work. Notably, team members are encouraged to minimize effort put towards course work. While courses are certainly important, they are not the priority in our graduate program. 
        -   **Research with other lab groups**. Its common for team members to work on previous research (i.e., publishing their previous MS work), develop collaborative projects, and even develop proposals with future mentors. When opportunities like this arise, it's important to (i) be transparent with Lab PI, and (ii) prioritize thesis/dissertation research. 
        -   **Service**. Team members are encouraged to become active members of both the university and larger scientific community. This includes being part of student clubs (e.g., BGSA, Steminist, etc) and volunteering for scientific society (e.g., AGU-H3S). However, these activities are in addition to their normal 40-hour week.
        -   **Consulting work**. Team members are discouraged from doing consulting work. If they do decide to do this, they need to ensure they are not breaching their UA contract and the work does not interfere with their research.
    -   **Work from the office regularly**. Unless problems arise, team members are free to work wherever they are most productive (i.e., library, coffee shop, home, etc). However, as a general rule, team members should work from the office at least 2 days per week. 
    -   **Work during regular business hours**. Team members should generally be available from 8AM to 5PM to communicate with the rest of the team. (Of course there's flexibility here with field work, classes, team meetings, etc...) 
    -   **Be active community members**. Attend regular lab meetings, support lab activities, and help other team members with their research. 
    -   **Consider tracking your hours**.  In most cases, team members will not be required to track their hours. However, there are many benefits (e.g., having a realistic understanding of effort allocation, reducing 'wasted time', and providing concrete data to discuss being "over-scoped" with Lab PI.) See Sam Zippers blog for a great example ([click here](https://www.samzipper.com/post/2022-01-02-work-tracking-update/)).

8.  **We will prioritize our well-being**.  Grad school is hard, and often the stress can cause and/or exacerbate mental health problems.  Below are a few guidelines to prevent burnout:

    -   **Work hard-play hard.** When you're at work, focus on your work. While we encourage community building, it's important to balance 'water cooler visits' with productivity. When you're outside of work, focus on being present in the moment. There's more to life than your degree...

    -   **12-hour rule.** When you leave work, try not to come back for 12-hours. 

    -   **If you're sick, stay home.** If you can work, awesome. If not, focus on resting and recovery. Sick days do not count towards your vacation time.   

    -   **Take regular vacations**. Everyone has different needs in regards to time off, but team members are expected to make sure those needs are being met. See point 9 below for parameters to work within.

9.  **We will take vacations**. Below are guidelines

    -   **Plan to take roughly 2-weeks (10 days) of vacation**.

    -   **Staff holidays ([click here](https://hr.ua.edu/payroll/payroll-schedules)) are in addition to the 2-weeks of vacation.** Notably, Spring Break is an exception and students are expected to make progress on their research that week. 

    -   **Weekends are your time**, and you should minimize(!) work during those periods. On the rare occasion you do work over a weekend, please make sure to "comp" yourself the time during the next week.

    -   **Notify Team PI at least** 1-week before departure and make sure to put it on the lab calendar 

    -   **Before going on vacation**, team members are expected to ensure all of their responsibilities are 

10. **We are going to have a lot of fun!**
